name = "VaccineStockManagementWithMDPs"
uuid = "f083925f-d207-4c3a-9ee2-f6db8fcb8566"
authors = ["Saul Diaz Infante Velasco", "Yofre Hernan Garcia Gomez"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
